### ISSUE TITLE
hlibBladeRF-0.1.0.2 test suite failure

### ISSUE THREAD

**Issue by peti** [victoredwardocallaghan/hlibBladeRF#4] opened 2015-03-06 10:40 UTC
Our CI environment found the following problems at http://hydra.cryp.to/build/607117/log/raw:
1. The test suite tries to call `cabal`, but `cabal-install` is not declared as a build-tool for the test suite.
2. hlint complains about possible optimizations.

I hope this helps.

**Comment by victoredwardocallaghan** [comment] 2015-03-06 12:35
Hi Peter,

First thanks for reporting this. I'm actually aware of the test-suite failure, although the package works fine regardless.

The issue is as follows; Haddock is uselessly including Bindings.X.Y in the coverage and there seems to be no way to stop that. This makes the Haddock test fail along with another blocker https://github.com/haskell/haddock/issues/370

In regards to the Hlint failure, that will be fixed shortly, the issues are purely cosmetic due to this package being in flux as it is so new.

If you have any tips on fixing the Haddock issues please do let me know.
Kind Regards,
Edward O'Callaghan.

**Comment by victoredwardocallaghan** [comment] 2015-03-06 16:41
Partial fix in commit a758aeaa6608bb36da1f9aabe591f4e42b2fbc9b

HLint is clean again.

**Comment by victoredwardocallaghan** [comment] 2015-03-06 20:48
Resolved in commit 75f1b4054fa6e3bf39228b2a64a96f2711fd7659

**Closed as completed by victoredwardocallaghan** 2015-03-06 20:48 UTC
Labels: bug

**Comment by peti** [comment] 2015-03-07 12:18
Thank you  very much for the quick response!
